config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  root "movies#index"
  # namespace :admin do
  #   root 'movies#index'
  # end //for this access through /admin and view and controller must be in admin folder and controller class must be inside module

  resources :movies

  # get "movies" => "movies#index"
  # get "movies/new" => "movies#new", as:"new_movie"
  # get "movies/:id" => "movies#show", as:"movie"
  # get "movies/:id/edit" => "movies#edit", as:"edit_movie"
  # patch "movies/:id" => "movies#update"
  # post "movies" => "movies#create"
  # delete "movies/:id" => "movies#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  def self.released
    where("released_on < ?",Time.now).order("released_on")
  end
  def floop?
    total_gross < 50000
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.released
  end
  def show
    @movie = Movie.find(params[:id])
  end
  def edit
    @movie = Movie.find(params[:id])
  end
  def new
    @movie = Movie.new
  end
  def create
    movie_data = movie_params
    @movie = Movie.create(movie_data)
    redirect_to @movie
  end
  def update
    @movie = Movie.find(params[:id])
    movie_data = movie_params
    @movie.update(movie_data) 
    redirect_to @movie
    # we can write @movie or movie_path(movies)
  end
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to root_url
  end
  private
  def movie_params
    params.require(:movie).permit(:title, :description, :rating, :total_gross, :released_on, :director, :duration, :image_file_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def total_gross(movie)
    if movie.floop?
      "floop!"
    else
      number_to_currency(movie.total_gross, precision:0)
    end
  end
  def year_of(movie)
    movie.released_on.strftime("%Y")
    # movie.released_on.year
  end
end

app/views/application/_header.html.erb
<header>
    <nav> 
      <%= link_to image_tag('logo.png'), root_path %>
      <ul>
        <li>
          <%= link_to "All Movies", movies_path %>
        </li>
      <ul>
    </nav>
  </header>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Copyright &copy; <%= Time.now.year %>
    This is a demo movie project referenced by <%= link_to "The Pragmatic Studio", "https://pragmaticstudio.com" %>
  </p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "header" %>
  <div class="content">
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model:movie) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title, autofocus:true %>

  <%= form.label :rating %>
  <%= form.text_field :rating %>

  <%= form.label :total_gross %>
  <%= form.number_field :total_gross %>

  <%= form.label :description %>
  <%= form.text_area :description ,row:5%>

  <%= form.label :released_on %>
  <%= form.date_field :released_on, {class: "date"}%>

  <%= form.label :director %>
  <%= form.text_field :director %>

  <%= form.label :duration %>
  <%= form.text_field :duration %>

  <%= form.label :image_file_name %>
  <%= form.text_field :image_file_name %>

  <%= form.submit %>
<% end %>

app/views/movies/edit.html.erb
<h2>Editing <%= @movie.title %></h2>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
  <section class="movie">
    <div class="image">
      <%= image_tag movie.image_file_name %>
    </div>
    <div class="summary">
      <h2>
        <%= link_to movie.title, movie %>
      </h2>
      <h3>
        <%= total_gross(movie)%>
      <h3>
      <p> 
        <%= truncate(movie.description, length: 60, separator: ' ') %>
      </p>
    </div>
  </section>
<% end %>
<section class="admin">
  <%= link_to "Create New Movie", new_movie_path, class:"button" %>
</section>

app/views/movies/new.html.erb
<h2>Create New Movie <%= @movie.title %></h2>

<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<section class="movie-details">
<div class="image">
  <%= image_tag @movie.image_file_name %>
</div>
<div class="details">
  <h1><%= @movie.title %></h1>
  <h2>
    <%= year_of(@movie) %> &bull; <%= @movie.rating %>
  </h2>
  <p>
    <%= @movie.description %>
  </p>
  <table>
    <tr>
      <th>Director:</th>
      <td><%= @movie.director %></td>
    </tr>
    <tr>
      <th>Duration:</th>
      <td><%= @movie.duration %></td>
    </tr>
    <tr>
      <th>Total Gross:</th>
      <td><%= total_gross(@movie) %></td>
    </tr>
  </table>
</div>
</section>
<section class="admin">
  <%= link_to "Edit", edit_movie_path(@movie), class:"button"%>
  <%= link_to "Delete", movie_path(@movie), class:"button", data: {turbo_method: :delete, turbo_confirm: "Sure to delete"}%>
</section>